# LOAD LIBRARY

In [1]:
! pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 7.7 MB/s eta 0:00:00a 0:00:01
Downloading numpy-2.4.3-cp312-cp312-macosx_11_0_arm64.whl (14.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.7/14.7 MB 5.8 MB/s eta 0:00:00a 0:00:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.3 pandas-3.0.1

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd

# LOAD DATASET

In [10]:
df1 = pd.read_csv("data/ALLARMI.csv")
df2 = pd.read_csv("data/TIPOLOGIA_VIAGGIATORE.csv")

In [11]:
df1

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,CITTA_PARTENZA,...,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,CODICE PAESE ARR,3zona,paese%arr,tot voli
0,Voli con Allarmi,FCO,IST,2024,01,2024-01-30 09:15:00,Fiumicino,Havalimani,Roma,Istanbul,...,5,1,Manuale,NaN,NaN,Turchia,ITA,5,Italia,1
1,Viaggiatori con Allarmi,CIA,STN,2024,02,2024-02-03 13:15:00,Ciampino,Stansted,Roma,Londra,...,5,5,Manuale,NaN,NaN,Regno Unito,ITA,5,Italia,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024,01,2024-01-15 08:45:00,Fiumicino,London Heathrow,Roma,Londra,...,5,110,TSC,NaN,NaN,Regno Unito,ITA,5,Italia,110
3,Voli con Allarmi,MXP,LHR,2024,02,2024-02-02 08:40:00,Malpensa,London Heathrow,Milano,Londra,...,2,1,SDI,NaN,NaN,Regno Unito,ITA,2,Italia,1
4,Viaggiatori con Allarmi,PSA,BRS,2024,02,2024-02-16 12:50:00,Galileo Galilei,Bristol,Pisa,Bristol,...,8,2,INTERPOL,NaN,NaN,Regno Unito,ITA,8,Italia,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5075,Nulla a procedere SDI,MXP,LTN,2023,01,2024-01-19 17:30:00,Malpensa,London Luton,Milano,Londra,...,2,5,TSC,NaN,NaN,Regno Unito,ITA,2,Italia,5
5076,Voli disponibili in ingresso al Sistema,BLQ,RAK,2024,02,FEB 06 2024,Guglielmo Marconi,Menara,Bologna,Marrakech,...,8,1,TSC,NaN,NaN,Marocco,ITA,8,Italia,1
5077,Voli con Allarmi,FCO,DOH,2024,01,2024-01-12 15:35:00,Fiumicino,Hamad International,Roma,Doha,...,5,1,NSIS,NaN,NaN,Qatar,ITA,5,Italia,1
5078,"Voli solo visualizzati, ma NON investigati",LIN,LHR,2024,01,2024-01-13 11:50:00,Linate,London Heathrow,Milano,Londra,...,2,1,TSC,NaN,NaN,Regno Unito,ITA,2,Italia,1
5079,Voli investigati (SDI/NSIS - INTERPOL - TSC),PSA,LGW,2024,02,2024-02-26 13:30:00,Galileo Galilei,London Gatwick,Pisa,Londra,...,8,1,TSC,NaN,NaN,Regno Unito,ITA,8,Italia,1

In [12]:
df2

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,GIORNO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,...,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio,Tipo Documento,FASCIA ETA,3nazionalita,compagnia%aerea,num volo
0,ALB,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,...,Fly Dubai,FZ1681,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,NaN,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,...,ITA Airways,AZ0609,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,ALB,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,...,Ryanair DAC,FR8400,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,AFG,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,...,Turkish Airlines,TK1865,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,ALB,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,...,Fly Dubai,FZ1571,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5090,ALB,BLQ,TIA,2024,02,15,2024-02-18 09:10:00,Guglielmo Marconi,Rinas Mother Teresa,Bologna,...,Ryanair DAC,FR8399,NaN,NaN,NaN,N.D.,0-17,ALB,Ryanair DAC,FR8399
5091,ALB,FCO,TIA,2024,01,10,2024-01-10 06:10:00,Fiumicino,Rinas Mother Teresa,Roma,...,Wizz Air Malta,W43857,NaN,NaN,NaN,Passaporto,46-60,ALB,Wizz Air Malta,W43857
5092,ALB,FCO,JED,2024,01,31,31/01/2024 22:15:00,Fiumicino,King Abdulaziz International,Roma,...,Wizz Air Malta,w48350,FERMATO,NaN,NaN,N.D.,31-45,ALB,Wizz Air Malta,w48350
5093,ALB,BGY,TIA,2024,01,1,2024-01-01 08:25:00,Orio al Serio,Rinas Mother Teresa,Bergamo,...,Ryanair DAC,FR8350,IN ATTESA,NaN,NaN,Carta d'identità,18-30,ALB,Ryanair DAC,FR8350
5094,ALB,FCO,MIA,2024,01,12,2024-01-12 19:50:00,Fiumicino,Miami International,Roma,...,ITA Airways,NaN,FERMATO,NaN,NaN,Carta d'identità,61+,ALB,ITA Airways,AZ0631